# Generated by Django 5.2.3 on 2025-08-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_user_last_streak_date_user_streak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('current_day', models.IntegerField(default=0)),
                ('last_log_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='HabitJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('entry', models.TextField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='habit_tracker.habit')),
            ],
            options={
                'unique_together': {('habit', 'day')},
            },
        ),
    ]
