# Generated by Django 5.2.3 on 2025-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_remove_habit_completed_habit_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='status',
        ),
        migrations.AddField(
            model_name='habit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(),
        ),
    ]
