# Generated by Django 5.2.3 on 2025-08-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0005_remove_habit_status_habit_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='lives',
            field=models.IntegerField(default=3),
        ),
    ]
