# Generated by Django 5.2.3 on 2025-08-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_habit_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='avatar',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
