# Generated by Django 5.2.3 on 2025-06-28 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_text', models.TextField()),
                ('emotion_1', models.CharField(max_length=30)),
                ('score_1', models.FloatField()),
                ('emotion_2', models.CharField(blank=True, max_length=30, null=True)),
                ('score_2', models.FloatField(blank=True, null=True)),
                ('emotion_3', models.CharField(blank=True, max_length=30, null=True)),
                ('score_3', models.FloatField(blank=True, null=True)),
                ('top_emotion_sentences', models.TextField(help_text='Sentences triggering top emotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
