# Generated by Django 5.2.3 on 2025-07-17 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journalentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
