# Generated by Django 5.2.3 on 2025-07-10 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('type_of_task', models.CharField(choices=[('DO', 'Do This'), ('DECIDE', 'Decide This'), ('DELEGATE', 'Delegate This'), ('DELETE', 'Delete This')], max_length=10)),
                ('ideal_time', models.DurationField()),
                ('taken_time', models.DurationField()),
                ('net_time', models.DurationField()),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('reflection', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
