# Generated by Django 5.2.3 on 2025-07-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivity',
            name='net_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
