# Generated by Django 5.2.3 on 2025-07-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_alter_productivity_net_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivity',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
