# Generated by Django 5.2.3 on 2025-07-14 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_alter_productivity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivity',
            name='taken_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
