# Generated by Django 5.2.3 on 2025-08-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0004_alter_productivity_taken_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productivity',
            name='net_time',
        ),
        migrations.AlterField(
            model_name='productivity',
            name='day',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
