# Generated by Django 5.2.3 on 2025-08-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0005_remove_productivity_net_time_alter_productivity_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivity',
            name='net_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productivity',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
