# Generated by Django 5.2.3 on 2025-08-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0006_productivity_net_time_alter_productivity_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivity',
            name='day',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
