# Generated by Django 5.2.3 on 2025-07-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
